- name: install catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: add system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      comment: "roboshop system user"
      home: /app
      system: true

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent   

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: delete app directory
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent   

  - name: download catalogue
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: unzip catalogue file
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    community.general.npm:
      path: /app
  
  - name: copy catalogue sercice
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: copy repo file
    ansible.builtin.template:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check whether catalogue db alresdy exists
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'  
    register: db_output

  - name: print db_output
    ansible.builtin.debug:
      msg: "{{ db_output }}"  

  - name: load catalogue products 
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: db_output.stdout | int < 0

  - name: daemon reload 
    ansible.builtin.systemd_service:
      name: catalogue
      daemon_reload: true

  - name: enable and start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes
     
