- name: install user
  hosts: user
  become: yes
  tasks:
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nginx:1.24 -y
    
  - name: install nodejs
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: delete file
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent  

  - name: download frontend
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip
      
  - name: unzip frontend file
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /app
      remote_src: yes

  - name: copy frontend sercice
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: enable and start frontend
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes

  

