- name: install user
  hosts: user
  become: yes
  tasks:
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: add system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      comment: "roboshop system user"
      home: /app
      system: true
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download user
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  - name: unzip user file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    community.general.npm:
      path: /app
  
  - name: copy user sercice
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: daemon reload 
    ansible.builtin.systemd_service:
      name: user
      daemon_reload: true

  - name: enable and start user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes
     
